# Site settings
title: the readme
email: knockknock@theread.me
description: a rabbit hole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://theread.me" # the base hostname & protocol for your site
twitter_username: mdibaiee
github_username:  mdibaiee
repo: "https://github.com/mdibaiee/theread.me"

date_format: "%b %d, %Y"

# Build settings
markdown: kramdown
permalink: /:title/
redcarpet:
  extensions: ["strikethrough"]

collections:
  math:
    title: math
    output: true
    permalink: /math/:path/
    path: /math
  programming:
    title: programming
    output: true
    permalink: /programming/:path/
    path: /programming
  life:
    title: life
    output: true
    permalink: /life/:path/
    path: /life
  travel:
    title: travel
    output: true
    permalink: /travel/:path/
    path: /travel

contentsLabel: "Table of Contents"
showToggleButton: true

authors:
  Mahdi:
    url: https://github.com/mdibaiee/
