# Site settings
title: Mahdi Dibaiee
email: mdibaiee@aol.com
description: Mahdi Dibaiee's personal blog on programming
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://dibaiee.ir" # the base hostname & protocol for your site
twitter_username: mdibaiee
github_username:  mdibaiee

# Build settings
markdown: kramdown
